spec:
  template:
    spec:
      initContainers:
      - name: otel-init
        image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
        command: ["cp", "-r", "/autoinstrumentation/.", "/otel-auto-instrumentation/"]
        volumeMounts:
        - name: otel-auto-instrumentation
          mountPath: /otel-auto-instrumentation
      containers:
      - name: server
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://$(NODE_IP):4317"
        - name: OTEL_SERVICE_NAME
          value: "recommendationservice"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "deployment.environment=assessment,service.version=0.10.4"
        - name: OTEL_PROPAGATORS
          value: "tracecontext,baggage"
        - name: PYTHONPATH
          value: "/otel-auto-instrumentation/auto_instrumentation:/otel-auto-instrumentation"
        volumeMounts:
        - name: otel-auto-instrumentation
          mountPath: /otel-auto-instrumentation
      volumes:
      - name: otel-auto-instrumentation
        emptyDir: {}
