apmConfig:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      secret_token: "myAssessmentSecretToken123"
      rum:
        enabled: true
        allow_origins: ["*"]

    output.elasticsearch:
      hosts: ["https://elasticsearch-master:9200"]
      username: "elastic"
      password: "EJTBz0UxOnhgSoA6"
      ssl.verification_mode: none

    setup.template.enabled: true
    setup.template.overwrite: true
    setup.ilm.enabled: true

    logging.level: info
    logging.to_files: false
